---
- name: Playbook to configure AAP
  hosts: localhost
  gather_facts: false
 
  pre_tasks:
    - name: Include specific project variables
      ansible.builtin.include_vars:
        dir: group_vars

  tasks:
    !
    !
    - name: Import role-aap-object-exec-env
      ansible.builtin.include_role:
        name: role-aap-object-exec-env
      vars:
        build: false
        name: "{{ item }}-exec-env"
        image_fqn: "{{ private_quay_root_name }}/{{ item }}-exec-env"
        description: "{{ common_description }}"
        registry_credential: "{{ private_quay_credential_name }}"
        validate_certs: false
        pull_state: "always"
      loop:
        - f5
        - fbb
        - custom-network
        - fortios
        - junos
        - mcn
    !
    !