---
# Define an execution environment
- name: "Build {{ name }} execution environment"
  ansible.controller.execution_environment:
    name: "{{ name }}"
    image: "{{ image_fqn }}"
    description: "{{ description }}"
    credential: "{{ registry_credential }}"
    validate_certs: "{{ validate_certs }}"
    state: "present"
    # organization: left blank so that it becomes Globally available.
    pull: "{{ pull_state }}" # Incase image is updated at source
  ignore_errors: true

# NB: After this successfully runs, you need to ensure the associated 
# credential has "Verify SSL" unselected!