---
# Define an execution environment
- name: "Build {{ in_list[0] }} execution environment"
  ansible.controller.execution_environment:
    name: "{{ in_list[0] }}"
    image: "{{ in_list[1] }}"
    description: "{{ in_list[2] }}"
    credential: "{{ in_list[3] }}"
    validate_certs: "{{ in_list[4] }}"
    state: "present"
    # organization: left blank so that it becomes Globally available.
    pull: "{{ in_list[5] }}" # Incase image is updated at source
  ignore_erros: true

# NB: After this successfully runs, you need to ensure the associated 
# credential has "Verify SSL" unselected!